# Parametry dla pipeline'u data_engineering
data_engineering:
  raw_data_path: "data/01_raw/PokemonData"

# Parametry dla pipeline'u data_science
data_science:
  # Parametry podziału danych
  split:
    test_size: 0.22
    random_state: 42
    target_column: "label"

  # Parametry treningu AutoGluon
  autogluon:
    time_limit: 600
    presets: "medium_quality"
    eval_metric: "accuracy"
