# Parametry dla pipeline'u data_engineering
data_engineering_params:
  raw_data_path: "data/01_raw/PokemonData"

# Parametry dla pipeline'u data_science
data_science_params:
  # Parametry podziału danych
  test_size: 0.22
  random_state: 42
  target_column: "label"

  # Parametry treningu AutoGluon
  autogluon:
    time_limit: 600  # w sekundach
    presets: "medium_quality"
    eval_metric: "accuracy"