# .pre-commit-config.yaml

repos:
  # ------------------------------------------------------------------------- #
  # Ogólne hooki
  # ------------------------------------------------------------------------- #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=5000]
      - id: detect-private-key
      - id: requirements-txt-fixer

  # ------------------------------------------------------------------------- #
  # Black - automatyczny formater kodu Pythona
  # ------------------------------------------------------------------------- #
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Używamy aktualnej wersji
    hooks:
      - id: black

  # ------------------------------------------------------------------------- #
  # Ruff - super-szybki linter i fixer. Zastępuje flake8 i isort.
  # ------------------------------------------------------------------------- #
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [ --fix, --unsafe-fixes, --exit-non-zero-on-fix ]

  # ------------------------------------------------------------------------- #
  # mypy - statyczna analiza typów (pozostaje bez zmian)
  # ------------------------------------------------------------------------- #
# .pre-commit-config.yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        # Dodaj pakiety stubów tutaj
        additional_dependencies: ['pyspark', 'types-requests']
