name: Zbuduj i Wdróż Aplikację Streamlit na ACI

on:
  push:
    branches: [ azure_test]
  workflow_dispatch:

env:
  # Sekrety i nazwy zdefiniowane w GitHub i Azure
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_REPOSITORY_NAME: ${{ secrets.ACR_REPOSITORY_NAME }}
  ACI_CONTAINER_NAME: ${{ secrets.ACI_CONTAINER_NAME }}
  ACI_DNS_NAME_LABEL: ${{ secrets.ACI_DNS_NAME_LABEL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Kroki budowania obrazu - pozostają takie same
    - name: 'Pobierz kod (Checkout)'
      uses: actions/checkout@v4

    - name: 'Zaloguj się do Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Zaloguj się do Azure Container Registry (ACR)'
      run: |
        az acr login --name $ACR_LOGIN_SERVER

    - name: 'Zbuduj i wypchnij obraz Docker'
      run: |
        docker build -f asi-project/Dockerfile . -t $ACR_LOGIN_SERVER/$ACR_REPOSITORY_NAME:${{ github.sha }}
        docker push $ACR_LOGIN_SERVER/$ACR_REPOSITORY_NAME:${{ github.sha }}

    # Nowy krok: Wdrożenie na ACI
    - name: 'Wdróż na Azure Container Instances (ACI)'
      run: |
        # Krok A: Usuń poprzednią wersję kontenera, jeśli istnieje.
        # "|| true" sprawia, że krok nie zakończy się błędem, jeśli kontener nie istnieje (przy pierwszym uruchomieniu).
        az container delete --name $ACI_CONTAINER_NAME --resource-group $RESOURCE_GROUP --yes || true

        # Krok B: Stwórz nowy kontener z najnowszym obrazem.
        az container create \
          --resource-group $RESOURCE_GROUP \
          --name $ACI_CONTAINER_NAME \
          --image $ACR_LOGIN_SERVER/$ACR_REPOSITORY_NAME:${{ github.sha }} \
          --dns-name-label $ACI_DNS_NAME_LABEL \
          --ports 8501 \
          --cpu 1 \
          --memory 1.5

        # Uwaga: Nie podajemy tu --registry-username i --registry-password.
        # Działa to, ponieważ zalogowaliśmy się do Azure za pomocą Service Principal,
        # który ma uprawnienia 'Contributor' do grupy zasobów, co pozwala mu na
        # automatyczne uwierzytelnienie się i pobranie obrazu z ACR w tej samej grupie.