name: Build and Push Docker Image with DVC + GDrive + GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install DVC with GDrive support
      run: pip install dvc[gdrive]

    - name: Restore GDrive config for DVC
      run: |
        mkdir -p ~/.config/gdrive
        echo "${{ secrets.GCP_SA_KEY_JSON }}" | base64 -d > gdrive_config.tar.gz
        tar xzf gdrive_config.tar.gz -C ~/.config/gdrive --strip-components=1

    - name: Pull data and model via DVC
      run: dvc pull

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/asi_app
        docker build -t $IMAGE_NAME:${{ github.sha }} .

    - name: Push Docker image (commit SHA tag)
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/asi_app
        docker push $IMAGE_NAME:${{ github.sha }}

    - name: (Optional) Tag and push latest for main
      if: github.ref == 'refs/heads/main'
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/asi_app
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
