name: Build and Push Docker Image with DVC + GDrive + GHCR

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install dvc[gdrive]

    - name: Write service account JSON key
      env:
        GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
      run: |
        echo "$GCP_SA_KEY_JSON" > /tmp/gdrive_sa_key.json

    - name: Run DVC setup script
      run: python .dvc/setup_dvc.py /tmp/gdrive_sa_key.json

    - name: Pull model via DVC
      run: dvc pull asi-project/AutogluonModels.dvc

    - name: Debug repo owner
      run: echo "Repository owner is ${{ github.repository_owner }}"

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/asi_app
        docker build -t $IMAGE_NAME:${{ github.sha }} ./asi-project

    - name: Push Docker image (commit SHA tag)
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/asi_app
        docker push $IMAGE_NAME:${{ github.sha }}

    - name: (Optional) Tag and push latest for main
      if: github.ref == 'refs/heads/main'
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/asi_app
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
